name: sb-runner
on:
  push:
    branches:
      - main
    paths:
      - build/sb-server-runner/**
  workflow_dispatch:
  schedule:
    - cron: '0 0 */10 * *'

jobs:
  build:
    uses: mchangrh/sb-mirror/.github/workflows/docker-build.yml@main
    with:
      name: "sb-server-runner"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}